//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindle_Cover_Fixer_V2 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kindle_Cover_Fixer_V2.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (To transfer files to your Kindle, it must be connected to your PC.).
        /// </summary>
        internal static string Aclaration {
            get {
                return ResourceManager.GetString("Aclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All book listed.
        /// </summary>
        internal static string BookListed {
            get {
                return ResourceManager.GetString("BookListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NAME.
        /// </summary>
        internal static string BookName {
            get {
                return ResourceManager.GetString("BookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOOK Nº.
        /// </summary>
        internal static string BookNumber {
            get {
                return ResourceManager.GetString("BookNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is on Kindle?.
        /// </summary>
        internal static string BookPassed {
            get {
                return ResourceManager.GetString("BookPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESULT.
        /// </summary>
        internal static string BookStatus {
            get {
                return ResourceManager.GetString("BookStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UUID.
        /// </summary>
        internal static string BookUuid {
            get {
                return ResourceManager.GetString("BookUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calibre library:.
        /// </summary>
        internal static string CalibreLib {
            get {
                return ResourceManager.GetString("CalibreLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At this point you can do three things:.
        /// </summary>
        internal static string CanDo {
            get {
                return ResourceManager.GetString("CanDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  | Can be transferred to Kindle: .
        /// </summary>
        internal static string CanTransfer {
            get {
                return ResourceManager.GetString("CanTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, check that you have a library correctly configured in Calibre..
        /// </summary>
        internal static string CheckLibrary {
            get {
                return ResourceManager.GetString("CheckLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot find Calibre library(s)..
        /// </summary>
        internal static string CheckLibraryTitle {
            get {
                return ResourceManager.GetString("CheckLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  - Find unsynced books -.
        /// </summary>
        internal static string CheckSync {
            get {
                return ResourceManager.GetString("CheckSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unussed cover deleted..
        /// </summary>
        internal static string Cleaned {
            get {
                return ResourceManager.GetString("Cleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cleaning unused Covers in Kindle.
        /// </summary>
        internal static string Cleaning {
            get {
                return ResourceManager.GetString("Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  cover(s).
        /// </summary>
        internal static string Covers {
            get {
                return ResourceManager.GetString("Covers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failure on: .
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find books.
        /// </summary>
        internal static string FindBooks {
            get {
                return ResourceManager.GetString("FindBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All cover(s) can be generated, total: .
        /// </summary>
        internal static string FindFinish {
            get {
                return ResourceManager.GetString("FindFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finding books in your library....
        /// </summary>
        internal static string Finding {
            get {
                return ResourceManager.GetString("Finding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Job finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All the books in your library are listed in the table..
        /// </summary>
        internal static string FinishListing {
            get {
                return ResourceManager.GetString("FinishListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate Covers.
        /// </summary>
        internal static string GenerateCovers {
            get {
                return ResourceManager.GetString("GenerateCovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All cover(s) generated, total: .
        /// </summary>
        internal static string Generated {
            get {
                return ResourceManager.GetString("Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generating new covers....
        /// </summary>
        internal static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t generate: .
        /// </summary>
        internal static string GeneratingError {
            get {
                return ResourceManager.GetString("GeneratingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The unused covers in in your Kindle was deleted..
        /// </summary>
        internal static string KindleClean {
            get {
                return ResourceManager.GetString("KindleClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean finished.
        /// </summary>
        internal static string KindleCleanTitle {
            get {
                return ResourceManager.GetString("KindleCleanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device not connected.
        /// </summary>
        internal static string KindleNone {
            get {
                return ResourceManager.GetString("KindleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kindle (Other).
        /// </summary>
        internal static string KindleOther {
            get {
                return ResourceManager.GetString("KindleOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kindle Scribe.
        /// </summary>
        internal static string KindleScribe {
            get {
                return ResourceManager.GetString("KindleScribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The covers have been transferred to Kindle. All that&apos;s left to do is enjoy!.
        /// </summary>
        internal static string KindleTransfer {
            get {
                return ResourceManager.GetString("KindleTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files Transferred.
        /// </summary>
        internal static string KindleTransferTitle {
            get {
                return ResourceManager.GetString("KindleTransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (New version available).
        /// </summary>
        internal static string NewVersionAv {
            get {
                return ResourceManager.GetString("NewVersionAv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to download and install the new version? \r\n \r\n You will get the following features: \r\n  \r\n.
        /// </summary>
        internal static string NewVersionWant {
            get {
                return ResourceManager.GetString("NewVersionWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New version available!.
        /// </summary>
        internal static string NewVersionWantTitle {
            get {
                return ResourceManager.GetString("NewVersionWantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generated covers will not be able to be transferred to the Kindle if no cover corresponds to a book currently on Kindle..
        /// </summary>
        internal static string NotTransferible {
            get {
                return ResourceManager.GetString("NotTransferible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  of .
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The covers in Output folder was deleted..
        /// </summary>
        internal static string OutputClean {
            get {
                return ResourceManager.GetString("OutputClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean finished.
        /// </summary>
        internal static string OutputCleanTitle {
            get {
                return ResourceManager.GetString("OutputCleanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready..
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⦁ Close this window to do nothing (Close)..
        /// </summary>
        internal static string ThingOne {
            get {
                return ResourceManager.GetString("ThingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ⦁ Transfer files directly to your Kindle (Transfer).
        /// </summary>
        internal static string ThingTwo {
            get {
                return ResourceManager.GetString("ThingTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer files.
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Covers transferred.
        /// </summary>
        internal static string Transferred {
            get {
                return ResourceManager.GetString("Transferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfering covers....
        /// </summary>
        internal static string Transferring {
            get {
                return ResourceManager.GetString("Transferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer to Kindle.
        /// </summary>
        internal static string TransferToKindle {
            get {
                return ResourceManager.GetString("TransferToKindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All covers have been generated.
        /// </summary>
        internal static string TransTitle {
            get {
                return ResourceManager.GetString("TransTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Up to date).
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
